In [1]:
from pathlib import Path
import pandas as pd
from collections import defaultdict
import yaml

def get_project_root():
    return Path().resolve().parent


# This file is the master mapping from city to province, the comprehensivre list with codes
# there are 514 unique districts/cities, and 38 unique provinces

df = pd.read_csv(get_project_root() / "data" / "mapping" / "master_2024.csv")
df

,nama_prov,value_prov,variable_kab,nama_kab,value_kab,kab,fullname,filename
0,ACEH,11,R102,SIMEULUE,1101,1,ACEH SIMEULUE,ACEH_SIMEULUE.txt
1,ACEH,11,R102,ACEH SINGKIL,1102,2,ACEH ACEH SINGKIL,ACEH_ACEH_SINGKIL.txt
2,ACEH,11,R102,ACEH SELATAN,1103,3,ACEH ACEH SELATAN,ACEH_ACEH_SELATAN.txt
3,ACEH,11,R102,ACEH TENGGARA,1104,4,ACEH ACEH TENGGARA,ACEH_ACEH_TENGGARA.txt
4,ACEH,11,R102,ACEH TIMUR,1105,5,ACEH ACEH TIMUR,ACEH_ACEH_TIMUR.txt
...,...,...,...,...,...,...,...,...
509,PAPUA PEGUNUNGAN,97,R102,TOLIKARA,9704,4,PAPUA PEGUNUNGAN TOLIKARA,PAPUA_PEGUNUNGAN_TOLIKARA.txt
510,PAPUA PEGUNUNGAN,97,R102,MAMBERAMO TENGAH,9705,5,PAPUA PEGUNUNGAN MAMBERAMO TENGAH,PAPUA_PEGUNUNGAN_MAMBERAMO_TENGAH.txt
511,PAPUA PEGUNUNGAN,97,R102,YALIMO,9706,6,PAPUA PEGUNUNGAN YALIMO,PAPUA_PEGUNUNGAN_YALIMO.txt
512,PAPUA PEGUNUNGAN,97,R102,YAHUKIMO,9707,7,PAPUA PEGUNUNGAN YAHUKIMO,PAPUA_PEGUNUNGAN_YAHUKIMO.txt
513,PAPUA PEGUNUNGAN,97,R102,PEGUNUNGAN BINTANG,9708,8,PAPUA PEGUNUNGAN PEGUNUNGAN BINTANG,PAPUA_PEGUNUNGAN_PEGUNUNGAN_BINTANG.txt

In [ ]:
# create nested dict version of master mapping from master full name for quick reference
prov_mapping = defaultdict(list)

for _, row in df.iterrows():
    prov_mapping[row["nama_prov"]].append(row["fullname"])

prov_mapping = dict(prov_mapping)

output_path = get_project_root() / "data" / "mapping"
output_path.mkdir(parents=True, exist_ok=True)

file_path = output_path / "prov_tree.yaml"

with open(file_path, "w", encoding="utf-8") as f:
    yaml.dump(
        prov_mapping,
        f,
        allow_unicode=True,
        sort_keys=True,
        default_flow_style=False
    )

In [3]:
# This is the raw data (policy) documents, not yet translated
base = Path.cwd().parent / "data" / "raw" / "localpolicies"
filenames = df["filename"].astype(str)

txt_exists = filenames.apply(lambda f: (base / f).exists())

pdf_exists = filenames.apply(
    lambda f: (base / Path(f).with_suffix(".pdf").name).exists()
)

print(f"Total rows: {len(df)}")
print(f"TXT exists: {txt_exists.sum()}")
print(f"TXT missing but PDF exists: {((~txt_exists) & pdf_exists).sum()}")
print(f"Missing entirely: {((~txt_exists) & (~pdf_exists)).sum()}")

Total rows: 514
TXT exists: 151
TXT missing but PDF exists: 6
Missing entirely: 357

In [4]:
# These are the manually coded assessments of the index indicators (by Hana)
# otherwise known as Hana's dataset
policy_encoding = pd.read_csv(get_project_root() / "data" / "raw" / "policy_encoding.csv")

prov_mapping = {
'ACEH': 'Aceh',
'SUMATERA UTARA': 'North Sumatera',
'SUMATERA BARAT': 'West Sumatera',
'RIAU': 'Riau',
'JAMBI': 'Jambi',
'SUMATERA SELATAN': 'South Sumatera',
'BENGKULU': 'Bengkulu',
'LAMPUNG': 'Lampung',
'KEPULAUAN BANGKA BELITUNG': 'Bangka Belitung',
'KEPULAUAN RIAU': 'Riau Islands',
'DKI JAKARTA': 'Jakarta Special Capital Region',
'JAWA BARAT': 'West Java',
'JAWA TENGAH': 'Central Java',
'DI YOGYAKARTA': 'Yogyakarta Special Region',
'JAWA TIMUR': 'East Java',
'BANTEN': 'Banten',
'BALI': 'Bali',
'NUSA TENGGARA BARAT': 'West Nusa Tenggara',
'NUSA TENGGARA TIMUR': 'East Nusa Tenggara',
'KALIMANTAN BARAT': 'West Kalimantan',
'KALIMANTAN TENGAH': 'Central Kalimantan',
'KALIMANTAN SELATAN': 'South Kalimantan',
'KALIMANTAN TIMUR': 'East Kalimantan',
'KALIMANTAN UTARA': 'North Kalimantan',
'SULAWESI UTARA': 'North Sulawesi',
'SULAWESI TENGAH': 'Central Sulawesi',
'SULAWESI SELATAN': 'South Sulawesi',
'SULAWESI TENGGARA': 'Southeast Sulawesi',
'GORONTALO': 'Gorontalo',
'SULAWESI BARAT': 'West Sulawesi',
'MALUKU': 'Maluku',
'MALUKU UTARA': 'North Maluku',
'PAPUA BARAT': 'West Papua',
'PAPUA BARAT DAYA': 'Southwest Papua',
'PAPUA': 'Papua',
'PAPUA SELATAN': 'South Papua',
'PAPUA TENGAH': 'Central Papua',
'PAPUA PEGUNUNGAN': 'Papua Pegunungan'
}
reverse_prov_mapping = {v: k for k, v in prov_mapping.items()}

policy_encoding['nama_prov'] = policy_encoding['Province'].map(reverse_prov_mapping)
policy_encoding

,City/Regency,Province,Year,POLICY ADOPTION,TOTAL POLICY SCORE,SCOPE OF VIOLENCE,1. Domestic violence,2. Sexual violence,3. Physical violence,4. Psychological violence,...,1. Local government budget,2. National government budget,3. International support/ donors,4. Other legal sources,5. Provincial government budget,Adoption of regulation establishing an Integrated Service Unit for Women and Children's Protection,Number of reported VAW cases (SIMFONI),Gross Regional Domestic Product (GDRP) at current market prices (billion Rupiah),New city/regency year of legal establishment,nama_prov
0,Simeulue,Aceh,2004,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0,NaN,ACEH
1,Simeulue,Aceh,2005,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,267.0,NaN,ACEH
2,Simeulue,Aceh,2006,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,332.0,NaN,ACEH
3,Simeulue,Aceh,2007,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,375.0,NaN,ACEH
4,Simeulue,Aceh,2008,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431.0,NaN,ACEH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11193,Kota Jayapura,Papua,2021,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17.0,33138.0,NaN,PAPUA
11194,Kota Jayapura,Papua,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,74.0,35365.0,NaN,PAPUA
11195,Kota Jayapura,Papua,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,37870.0,NaN,PAPUA
11196,Kota Jayapura,Papua,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.0,39815.0,NaN,PAPUA
11197,Kota Jayapura,Papua,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42212.0,NaN,PAPUA

In [6]:
# sort by province first
df_sorted = policy_encoding.sort_values("nama_prov")

# group by province and print unique City/Regency
for prov, group in df_sorted.groupby("nama_prov"):
    print(f"\n{prov}")
    print(group["City/Regency"].dropna().unique())

ACEH
<ArrowStringArray>
[         'Simeulue',      'Aceh Singkil',      'Aceh Selatan',
     'Aceh Tenggara',        'Aceh Timur',       'Aceh Tengah',
        'Aceh Barat',        'Aceh Besar',             'Pidie',
           'Bireuen',        'Aceh Utara',   'Aceh Barat Daya',
         'Gayo Lues',      'Aceh Tamiang',        'Nagan Raya',
         'Aceh Jaya',      'Bener Meriah',        'Pidie Jaya',
   'Kota Banda Aceh',       'Kota Sabang',       'Kota Langsa',
  'Kota Lhokseumawe', 'Kota Subulussalam']
Length: 23, dtype: str

BALI
<ArrowStringArray>
[     'Jembrana',       'Tabanan',        'Badung',       'Gianyar',
     'Klungkung',        'Bangli',    'Karangasem',      'Buleleng',
 'Kota Denpasar']
Length: 9, dtype: str

BANTEN
<ArrowStringArray>
[            'Pandeglang',                  'Lebak',              'Tangerang',
                 'Serang',         'Kota Tangerang',           'Kota Cilegon',
            'Kota Serang', 'Kota Tangerang Selatan']
Length: 8, dtype: str

BENGKULU
<ArrowStringArray>
['Bengkulu Selatan',    'Rejang Lebong',   'Bengkulu Utara',
             'Kaur',           'Seluma',         'Mukomuko',
           'Lebong',        'Kepahiang',  'Bengkulu Tengah',
    'Kota Bengkulu']
Length: 10, dtype: str

DI YOGYAKARTA
<ArrowStringArray>
['Kulon Progo', 'Bantul', 'Gunung Kidul', 'Sleman', 'Kota Yogyakarta']
Length: 5, dtype: str

DKI JAKARTA
<ArrowStringArray>
['DKI Jakarta']
Length: 1, dtype: str

GORONTALO
<ArrowStringArray>
[        'Boalemo',       'Gorontalo',        'Pohuwato',    'Bone Bolango',
 'Gorontalo Utara',  'Kota Gorontalo']
Length: 6, dtype: str

JAMBI
<ArrowStringArray>
[             'Kerinci',             'Merangin',           'Sarolangun',
          'Batang Hari',          'Muaro Jambi', 'Tanjung Jabung Timur',
 'Tanjung Jabung Barat',                 'Tebo',                'Bungo',
           'Kota Jambi',    'Kota Sungai Penuh']
Length: 11, dtype: str

JAWA BARAT
<ArrowStringArray>
[           'Bogor',         'Sukabumi',          'Cianjur',
          'Bandung',            'Garut',      'Tasikmalaya',
           'Ciamis',         'Kuningan',          'Cirebon',
       'Majalengka',         'Sumedang',        'Indramayu',
           'Subang',       'Purwakarta',         'Karawang',
           'Bekasi',    'Bandung Barat',      'Pangandaran',
       'Kota Bogor',    'Kota Sukabumi',     'Kota Bandung',
     'Kota Cirebon',      'Kota Bekasi',       'Kota Depok',
      'Kota Cimahi', 'Kota Tasikmalaya',      'Kota Banjar']
Length: 27, dtype: str

JAWA TENGAH
<ArrowStringArray>
[        'Cilacap',        'Banyumas',     'Purbalingga',    'Banjarnegara',
         'Kebumen',       'Purworejo',        'Wonosobo',        'Magelang',
        'Boyolali',          'Klaten',       'Sukoharjo',        'Wonogiri',
     'Karanganyar',          'Sragen',        'Grobogan',           'Blora',
         'Rembang',            'Pati',           'Kudus',          'Jepara',
           'Demak',        'Semarang',      'Temanggung',          'Kendal',
          'Batang',      'Pekalongan',        'Pemalang',           'Tegal',
          'Brebes',   'Kota Magelang',  'Kota Surakarta',   'Kota Salatiga',
   'Kota Semarang', 'Kota Pekalongan',      'Kota Tegal']
Length: 35, dtype: str

JAWA TIMUR
<ArrowStringArray>
[         'Pacitan',         'Ponorogo',       'Trenggalek',
      'Tulungagung',           'Blitar',           'Kediri',
           'Malang',         'Lumajang',           'Jember',
       'Banyuwangi',        'Bondowoso',        'Situbondo',
      'Probolinggo',         'Pasuruan',         'Sidoarjo',
        'Mojokerto',          'Jombang',          'Nganjuk',
           'Madiun',          'Magetan',            'Ngawi',
       'Bojonegoro',            'Tuban',         'Lamongan',
           'Gresik',        'Bangkalan',          'Sampang',
        'Pamekasan',          'Sumenep',      'Kota Kediri',
      'Kota Blitar',      'Kota Malang', 'Kota Probolinggo',
    'Kota Pasuruan',   'Kota Mojokerto',      'Kota Madiun',
    'Kota Surabaya',        'Kota Batu']
Length: 38, dtype: str

KALIMANTAN BARAT
<ArrowStringArray>
[         'Sambas',      'Bengkayang',          'Landak',        'Mempawah',
         'Sanggau',        'Ketapang',         'Sintang',     'Kapuas Hulu',
         'Sekadau',          'Melawi',    'Kayong Utara',       'Kubu Raya',
  'Kota Pontianak', 'Kota Singkawang']
Length: 14, dtype: str

KALIMANTAN SELATAN
<ArrowStringArray>
[         'Tanah Laut',           'Kota Baru',              'Banjar',
        'Barito Kuala',               'Tapin', 'Hulu Sungai Selatan',
  'Hulu Sungai Tengah',   'Hulu Sungai Utara',            'Tabalong',
         'Tanah Bumbu',            'Balangan',    'Kota Banjarmasin',
    'Kota Banjar Baru']
Length: 13, dtype: str

KALIMANTAN TENGAH
<ArrowStringArray>
['Kotawaringin Barat', 'Kotawaringin Timur',             'Kapuas',
     'Barito Selatan',       'Barito Utara',           'Sukamara',
           'Lamandau',            'Seruyan',           'Katingan',
       'Pulang Pisau',         'Gunung Mas',       'Barito Timur',
        'Murung Raya', 'Kota Palangka Raya']
Length: 14, dtype: str

KALIMANTAN TIMUR
<ArrowStringArray>
[              'Paser',         'Kutai Barat',   'Kutai Kartanegara',
         'Kutai Timur',               'Berau', 'Penajam Paser Utara',
         'Mahakam Ulu',     'Kota Balikpapan',      'Kota Samarinda',
        'Kota Bontang']
Length: 10, dtype: str

KALIMANTAN UTARA
<ArrowStringArray>
['Malinau', 'Bulungan', 'Tana Tidung', 'Nunukan', 'Kota Tarakan']
Length: 5, dtype: str

KEPULAUAN BANGKA BELITUNG
<ArrowStringArray>
[             'Bangka',            'Belitung',        'Bangka Barat',
       'Bangka Tengah',      'Bangka Selatan',      'Belitung Timur',
 'Kota Pangkal Pinang']
Length: 7, dtype: str

KEPULAUAN RIAU
<ArrowStringArray>
[            'Karimun',              'Bintan',              'Natuna',
              'Lingga',   'Kepulauan Anambas',          'Kota Batam',
 'Kota Tanjung Pinang']
Length: 7, dtype: str

LAMPUNG
<ArrowStringArray>
[      'Lampung Barat',           'Tanggamus',     'Lampung Selatan',
       'Lampung Timur',      'Lampung Tengah',       'Lampung Utara',
           'Way Kanan',       'Tulang Bawang',           'Pesawaran',
           'Pringsewu',              'Mesuji', 'Tulang Bawang Barat',
       'Pesisir Barat', 'Kota Bandar Lampung',          'Kota Metro']
Length: 15, dtype: str

MALUKU
<ArrowStringArray>
[        'Mamuju Tengah', 'Maluku Tenggara Barat',       'Maluku Tenggara',
         'Maluku Tengah',                  'Buru',         'Kepulauan Aru',
    'Seram Bagian Barat',    'Seram Bagian Timur',     'Maluku Barat Daya',
          'Buru Selatan',            'Kota Ambon',             'Kota Tual']
Length: 12, dtype: str

MALUKU UTARA
<ArrowStringArray>
[      'Halmahera Barat',      'Halmahera Tengah',        'Kepulauan Sula',
     'Halmahera Selatan',       'Halmahera Utara',       'Halmahera Timur',
         'Pulau Morotai',         'Pulau Taliabu',          'Kota Ternate',
 'Kota Tidore Kepulauan']
Length: 10, dtype: str

NUSA TENGGARA BARAT
<ArrowStringArray>
[ 'Lombok Barat', 'Lombok Tengah',  'Lombok Timur',       'Sumbawa',
         'Dompu',          'Bima', 'Sumbawa Barat',  'Lombok Utara',
  'Kota Mataram',     'Kota Bima']
Length: 10, dtype: str

NUSA TENGGARA TIMUR
<ArrowStringArray>
[         'Sumba Barat',          'Sumba Timur',               'Kupang',
 'Timor Tengah Selatan',   'Timor Tengah Utara',                 'Belu',
                 'Alor',              'Lembata',         'Flores Timur',
                'Sikka',                 'Ende',                'Ngada',
            'Manggarai',            'Rote Ndao',      'Manggarai Barat',
         'Sumba Tengah',     'Sumba Barat Daya',              'Nagekeo',
      'Manggarai Timur',          'Sabu Raijua',               'Malaka',
          'Kota Kupang']
Length: 22, dtype: str

PAPUA
<ArrowStringArray>
['Kepulauan Yapen',     'Biak Numfor',        'Jayapura',           'Sarmi',
          'Keerom',         'Waropen',         'Supiori',  'Mamberamo Raya',
   'Kota Jayapura']
Length: 9, dtype: str

PAPUA BARAT
<ArrowStringArray>
[           'Fakfak',           'Kaimana',     'Teluk Wondama',
     'Teluk Bintuni',         'Manokwari', 'Manokwari Selatan',
  'Pegunungan Arfak']
Length: 7, dtype: str

PAPUA BARAT DAYA
<ArrowStringArray>
['Sorong Selatan', 'Sorong', 'Raja Ampat', 'Tambrauw', 'Maybrat',
 'Kota Sorong']
Length: 6, dtype: str

PAPUA PEGUNUNGAN
<ArrowStringArray>
[        'Jayawijaya', 'Pegunungan Bintang',           'Tolikara',
   'Mamberamo Tengah',             'Yalimo',         'Lanny Jaya',
              'Nduga',           'Yahukimo']
Length: 8, dtype: str

PAPUA SELATAN
<ArrowStringArray>
['Merauke', 'Boven Digoel', 'Mappi', 'Asmat']
Length: 4, dtype: str

PAPUA TENGAH
<ArrowStringArray>
[     'Nabire',      'Paniai',      'Mimika', 'Puncak Jaya',      'Puncak',
     'Dogiyai',  'Intan Jaya',      'Deiyai']
Length: 8, dtype: str

RIAU
<ArrowStringArray>
[ 'Kuantan Singingi',    'Indragiri Hulu',   'Indragiri Hilir',
         'Pelalawan',              'Siak',            'Kampar',
        'Rokan Hulu',         'Bengkalis',       'Rokan Hilir',
 'Kepulauan Meranti',    'Kota Pekanbaru',        'Kota Dumai']
Length: 12, dtype: str

SULAWESI BARAT
<ArrowStringArray>
['Majene', 'Polewali Mandar', 'Mamasa', 'Mamuju', 'Mamuju Utara']
Length: 5, dtype: str

SULAWESI SELATAN
<ArrowStringArray>
[       'Kepulauan Selayar',                'Bulukumba',
                 'Bantaeng',                'Jeneponto',
                  'Takalar',                     'Gowa',
                   'Sinjai',                    'Maros',
 'Pangkajene dan Kepulauan',                    'Barru',
                     'Bone',                  'Soppeng',
                     'Wajo',        'Sidenreng Rappang',
                  'Pinrang',                 'Enrekang',
                     'Luwu',              'Tana Toraja',
               'Luwu Utara',               'Luwu Timur',
             'Toraja Utara',             'Kota Makasar',
            'Kota Parepare',              'Kota Palopo']
Length: 24, dtype: str

SULAWESI TENGAH
<ArrowStringArray>
['Banggai Kepulauan',           'Banggai',          'Morowali',
              'Poso',          'Donggala',         'Toli-Toli',
              'Buol',    'Parigi Moutong',      'Tojo Una-Una',
              'Sigi',      'Banggai Laut',    'Morowali Utara',
         'Kota Palu']
Length: 13, dtype: str

SULAWESI TENGGARA
<ArrowStringArray>
[           'Buton',             'Muna',           'Konawe',
           'Kolaka',   'Konawe Selatan',          'Bombana',
         'Wakatobi',     'Kolaka Utara',      'Buton Utara',
     'Konawe Utara',     'Kolaka Timur', 'Konawe Kepulauan',
       'Muna Barat',     'Buton Tengah',    'Buton Selatan',
     'Kota Kendari',      'Kota Baubau']
Length: 17, dtype: str

SULAWESI UTARA
<ArrowStringArray>
[        'Bolaang Mongondow',                  'Minahasa',
         'Kepulauan Sangihe',          'Kepulauan Talaud',
          'Minahasa Selatan',            'Minahasa Utara',
   'Bolaang Mongondow Utara',    'Siau Tagulandang Biaro',
         'Minahasa Tenggara', 'Bolaang Mongondow Selatan',
   'Bolaang Mongondow Timur',               'Kota Manado',
               'Kota Bitung',              'Kota Tomohon',
           'Kota Kotamobagu']
Length: 15, dtype: str

SUMATERA BARAT
<ArrowStringArray>
[ 'Kepulauan Mentawai',     'Pesisir Selatan',               'Solok',
           'Sijunjung',         'Tanah Datar',     'Padang Pariaman',
                'Agam',     'Lima Puluh Kota',             'Pasaman',
       'Solok Selatan',         'Dharmasraya',       'Pasaman Barat',
         'Kota Padang',          'Kota Solok',    'Kota Sawah Lunto',
 'Kota Padang Panjang',    'Kota Bukittinggi',     'Kota Payakumbuh',
       'Kota Pariaman']
Length: 19, dtype: str

SUMATERA SELATAN
<ArrowStringArray>
[         'Ogan Komering Ulu',         'Ogan Komering Ilir',
                 'Muara Enim',                      'Lahat',
                 'Musi Rawas',             'Musi Banyuasin',
                 'Banyu Asin',  'Ogan Komering Ulu Selatan',
    'Ogan Komering Ulu Timur',                  'Ogan Ilir',
               'Empat Lawang', 'Penukal Abab Lematang Ilir',
           'Musi Rawas Utara',             'Kota Palembang',
            'Kota Prabumulih',            'Kota Pagar Alam',
          'Kota Lubuklinggau']
Length: 17, dtype: str

SUMATERA UTARA
<ArrowStringArray>
[                 'Nias',      'Mandailing Natal',      'Tapanuli Selatan',
       'Tapanuli Tengah',        'Tapanuli Utara',          'Toba Samosir',
          'Labuhan Batu',                'Asahan',            'Simalungun',
                 'Dairi',                  'Karo',          'Deli Serdang',
               'Langkat',          'Nias Selatan',    'Humbang Hasundutan',
         'Pakpak Bharat',               'Samosir',       'Serdang Bedagai',
             'Batu Bara',    'Padang Lawas Utara',          'Padang Lawas',
  'Labuhan Batu Selatan',    'Labuhan Batu Utara',            'Nias Utara',
            'Nias Barat',          'Kota Sibolga',    'Kota Tanjung Balai',
 'Kota Pematang Siantar',    'Kota Tebing Tinggi',            'Kota Medan',
           'Kota Binjai', 'Kota Padang Sidempuan',     'Kota Gunungsitoli']
Length: 33, dtype: str

# Q for Hana:
['DKI Jakarta'] -> DKI JAKARTA:
- DKI JAKARTA KEPULAUAN SERIBU
- DKI JAKARTA JAKARTA SELATAN KOTA
- DKI JAKARTA JAKARTA TIMUR KOTA
- DKI JAKARTA JAKARTA PUSAT KOTA
- DKI JAKARTA JAKARTA BARAT KOTA
- DKI JAKARTA JAKARTA UTARA KOTA


MALUKU master has 11, 12 in Hana's dataset
SULAWESI BARAT master has 5, hanas dataset has 6

In [8]:
# there are 509 unique cities here 
policy_encoding[['Province','City/Regency']].nunique()

Province         38
City/Regency    509
dtype: int64

In [ ]:
with open(get_project_root() / "data" / "mapping"/"city_mapping.yaml", "r") as f:
    aceh_mapping = yaml.safe_load(f)

In [ ]:
aceh_mapping

{'ACEH SIMEULUE': 'Simeulue',
 'ACEH ACEH SINGKIL': 'Aceh Singkil',
 'ACEH ACEH SELATAN': 'Aceh Selatan',
 'ACEH ACEH TENGGARA': 'Aceh Tenggara',
 'ACEH ACEH TIMUR': 'Aceh Timur',
 'ACEH ACEH TENGAH': 'Aceh Tengah',
 'ACEH ACEH BARAT': 'Aceh Barat',
 'ACEH ACEH BESAR': 'Aceh Besar',
 'ACEH PIDIE': 'Pidie',
 'ACEH BIREUEN': 'Bireuen',
 'ACEH ACEH UTARA': 'Aceh Utara',
 'ACEH ACEH BARAT DAYA': 'Aceh Barat Daya',
 'ACEH GAYO LUES': 'Gayo Lues',
 'ACEH ACEH TAMIANG': 'Aceh Tamiang',
 'ACEH NAGAN RAYA': 'Nagan Raya',
 'ACEH ACEH JAYA': 'Aceh Jaya',
 'ACEH BENER MERIAH': 'Bener Meriah',
 'ACEH PIDIE JAYA': 'Pidie Jaya',
 'ACEH BANDA ACEH KOTA': 'Kota Banda Aceh',
 'ACEH SABANG KOTA': 'Kota Sabang',
 'ACEH LANGSA KOTA': 'Kota Langsa',
 'ACEH LHOKSEUMAWE KOTA': 'Kota Lhokseumawe',
 'ACEH SUBULUSSALAM KOTA': 'Kota Subulussalam'}

: