In [10]:
from pathlib import Path
import pandas as pd

def get_project_root():
    return Path().resolve().parent


reviewed = pd.read_csv(get_project_root().parent / "HH+error_analysis.csv", delimiter=";")
reviewed = reviewed[['fullname','indicator_id','golden_label_update']].iloc[:196].fillna('x')
to_review = pd.read_csv(get_project_root().parent / "error_analysis_RAG.csv")

In [11]:
reviewed

                   fullname  indicator_id golden_label_update
0              ACEH BIREUEN           4.2                   x
1              ACEH BIREUEN           5.1                 Yes
2              ACEH BIREUEN           5.4                   x
3              ACEH BIREUEN           5.5                 Yes
4              ACEH BIREUEN           6.8                 Yes
..                      ...           ...                 ...
191  JAWA BARAT TASIKMALAYA           3.1                   x
192  JAWA BARAT TASIKMALAYA           4.2                   x
193  JAWA BARAT TASIKMALAYA           5.3                   x
194  JAWA BARAT TASIKMALAYA           5.6                   x
195  JAWA BARAT TASIKMALAYA           6.6                 Yes

[196 rows x 3 columns]

In [12]:
to_review = to_review.merge(
    reviewed,
    on=["fullname", "indicator_id"],
    how="left"
)

In [13]:
to_review

,fullname,filename,indicator_id,indicator_value,dimension,golden_label,pred_label,value,pred_value,error_type,evidence,rationale,discrepancy_root_cause,golden_label_update
0,ACEH BIREUEN,ACEH_BIREUEN.txt,1.9,Sexual slavery / exploitation,scope_of_violence,Yes,No,1.0,0.0,false_negative,NaN,While exploitation is mentioned in employment ...,Reference only,NaN
1,ACEH BIREUEN,ACEH_BIREUEN.txt,3.7,Psychosocial counselling,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,"Although the policy references rehabilitation,...",Reference only,NaN
2,ACEH BIREUEN,ACEH_BIREUEN.txt,4.2,Gender equality education,primary_prevention,No,Yes,0.0,1.0,false_positive,Article 5\n(1) Every woman has the right to:\n...,"The policy explicitly sets out women’s rights,...",Reference only,x
3,ACEH BIREUEN,ACEH_BIREUEN.txt,4.4,Prevention through education,primary_prevention,No,Yes,0.0,1.0,false_positive,Article 25\n(1) The Regency Government is obli...,The policy includes prevention efforts through...,Reference only,NaN
4,ACEH BIREUEN,ACEH_BIREUEN.txt,5.1,NGO collaboration,stakeholder_engagement,No,Yes,0.0,1.0,false_positive,CHAPTER VIII\nCOMMUNITY PARTICIPATION\nArticle...,The policy provides for community participatio...,Reference only,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,SUMATERA UTARA PADANGSIDIMPUAN KOTA,SUMATERA_UTARA_PADANGSIDIMPUAN_KOTA.txt,6.3,Women workers,intersectional_approach,No,Yes,0.0,1.0,false_positive,Article 5\n(1) Every woman has the right to:\n...,The policy explicitly mentions work-related pr...,Reference only,NaN
1085,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,1.9,Sexual slavery / exploitation,scope_of_violence,No,Yes,0.0,1.0,false_positive,Article 3\n(1) The objectives of providing pro...,The policy states an objective to eliminate al...,Reference only,NaN
1086,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,3.1,Economic support services,specialised_support_services,Yes,No,1.0,0.0,false_negative,NaN,While prevention efforts mention access to tra...,Reference only,NaN
1087,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,4.2,Gender equality education,primary_prevention,No,Yes,0.0,1.0,false_positive,CHAPTER XII\nCOMMUNITY PARTICIPATION\nArticle ...,The policy explicitly mentions community-led s...,Reference only,NaN
1088,SUMATERA UTARA PAKPAK BHARAT,SUMATERA_UTARA_PAKPAK_BHARAT.txt,6.2,Trafficking victims,intersectional_approach,No,Yes,0.0,1.0,false_positive,Article 3\n(1) The objectives of providing pro...,The policy explicitly includes human trafficki...,Reference only,NaN

In [14]:
output_path = get_project_root().parent / "error_analysis_v2.csv"
to_review.to_csv(output_path, index=False)