In [46]:
from pathlib import Path
import pandas as pd

def get_project_root():
    return Path().resolve().parent


df = pd.read_csv(get_project_root().parent / "HH+error_analysis_v2.csv", delimiter=";")
df = df[df['golden_label_update']=='x']

# df = df[df['golden_label_update']!='x'].dropna(subset='golden_label_update')
# with pd.option_context('display.max_rows', None):
#     display(df[['filename', 'indicator_id', 'golden_label_update']])

## AI Error analysis

In [47]:
overall = (
    df.groupby("error_type")
      .size()
      .rename("count")
      .reset_index()
)

overall["percent"] = overall["count"] / len(df) * 100
overall

       error_type  count    percent
0  false_negative    102  59.302326
1  false_positive     70  40.697674

In [48]:
summary = (
    df.groupby("dimension")
      .agg(
          n=("dimension","size"),
          FP=("error_type", lambda x: (x=="false_positive").sum()),
          FN=("error_type", lambda x: (x=="false_negative").sum()),
      )
)

summary

                               n  FP  FN
dimension
budget_funding_sources         2   2   0
institutional_mechanism       29  13  16
intersectional_approach       35  20  15
primary_prevention            25  25   0
scope_of_violence             14   4  10
specialised_support_services  25   4  21
stakeholder_engagement        42   2  40

In [50]:
indicator_summary = (
    df.groupby(["indicator_id","indicator_value"])
      .agg(
          n=("indicator_id","size"),
          FP=("error_type", lambda x: (x=="false_positive").sum()),
          FN=("error_type", lambda x: (x=="false_negative").sum())
      )
      .reset_index()
)

indicator_summary = indicator_summary.sort_values("n",ascending=False)
indicator_summary

,indicator_id,indicator_value,n,FP,FN
30,6.2,Trafficking victims,14,0,14
24,5.2,Religious engagement,14,0,14
20,4.2,Gender equality education,13,13,0
11,2.5,Training and capacity building,12,10,2
25,5.3,Traditional/cultural engagement,12,1,11
17,3.8,Religious / spiritual counselling,9,1,8
22,4.4,Prevention through education,7,7,0
7,2.1,Institutional network / coordination mechanism,7,0,7
14,3.3,Reporting / hotline,6,0,6
28,5.8,Private sector engagement,6,0,6
34,6.8,Legal process involvement,6,6,0
31,6.3,Women workers,5,5,0
27,5.6,Media engagement,5,0,5
9,2.3,Data collection / information systems,5,3,2
26,5.4,Education institutions engagement,4,1,3
19,4.1,Information & education on VAW,4,4,0
10,2.4,Gender mainstreaming institutionalisation,4,0,4
32,6.5,Disability,4,4,0
5,1.8,Human trafficking,3,0,3
16,3.7,Psychosocial counselling,3,0,3
1,1.1,Technology-facilitated violence,2,2,0
35,6.9,Indigenous groups,2,2,0
4,1.6,Harmful practices,2,0,2
2,1.2,Sexual violence,2,0,2
3,1.5,Economic violence,2,1,1
12,3.1,Economic support services,2,2,0
6,1.9,Sexual slavery / exploitation,2,1,1
13,3.2,Police specialised service unit,2,1,1
15,3.4,Safety / protection shelter,2,0,2
29,6.1,Refugees / displacement,2,2,0
36,7.3,International donors,2,2,0
33,6.7,Minority groups,2,1,1
0,1.1,Domestic violence,1,0,1
18,3.9,Resocialisation services,1,0,1
8,2.2,Collaboration with non-government service prov...,1,0,1
21,4.3,VAW laws awareness,1,1,0
23,5.1,NGO collaboration,1,0,1

In [61]:
len(indicator_summary)

37

In [83]:
df62 = df[df["indicator_id"] ==5.1]

from IPython.display import display, HTML

display(
    HTML(
        df62[[
            "fullname",
            "evidence",
            "rationale",
            "explanation",
            "value",
            "pred_value"
        ]].to_html().replace(
            '<td>',
            '<td style="white-space: pre-wrap; word-wrap: break-word; max-width:600px;">'
        )
    )
)